# Theme Settings Configuration File

# use settings.yml file for configure colors, ui, rtl, sidebar, animation options

# Main Settings
settings:
  quick_colors: "" # select quick color schemes: "blue", "green", "orange", "pink", "purple", "red". If empty colors taken from _sass/ryancv/settings.scss
  dark_ui: 0 # activated dark ui styles
  rtl: 0 # activated rtl styles
  sidebar: 1 # for disable sidebar and sidebar button change to 0
  preloader: "Загрузка..." # preloader loading text

# # Portfolio Filters Settings
# portfolio:
#   filters:
#     - name: "Все"
#       slug: "box-item"
#       active: 1

#     - name: "Video"
#       slug: "f-video"
#       active: 0

#     - name: "Music"
#       slug: "f-music"
#       active: 0

#     - name: "Links"
#       slug: "f-link"
#       active: 0

#     - name: "Image"
#       slug: "f-image"
#       active: 0

#     - name: "Gallery"
#       slug: "f-gallery"
#       active: 0

#     - name: "Content"
#       slug: "f-content"
#       active: 0

# Vinyl Filters Settings
vinyl:
  filters:
    - name: "Все"
      slug: "box-item"
      active: 1

    - name: "A"
      slug: "f-content"
      active: 0

    # - name: "B"
    #   slug: "f-content"
    #   active: 0

    # - name: "C"
    #   slug: "f-content"
    #   active: 0

    # - name: "D"
    #   slug: "f-content"
    #   active: 0

    # - name: "E"
    #   slug: "f-content"
    #   active: 0

    # - name: "F"
    #   slug: "f-content"
    #   active: 0

    # - name: "H"
    #   slug: "f-content"
    #   active: 0

    # - name: "I"
    #   slug: "f-content"
    #   active: 0

    # - name: "J"
    #   slug: "f-content"
    #   active: 0

    # - name: "K"
    #   slug: "f-content"
    #   active: 0

    # - name: "L"
    #   slug: "f-content"
    #   active: 0

    - name: "M"
      slug: "f-content"
      active: 0

    # - name: "N"
    #   slug: "f-content"
    #   active: 0

    # - name: "O"
    #   slug: "f-content"
    #   active: 0

    # - name: "P"
    #   slug: "f-content"
    #   active: 0

    # - name: "Q"
    #   slug: "f-content"
    #   active: 0

    # - name: "R"
    #   slug: "f-content"
    #   active: 0

    # - name: "S"
    #   slug: "f-content"
    #   active: 0

    # - name: "T"
    #   slug: "f-content"
    #   active: 0

    # - name: "U"
    #   slug: "f-content"
    #   active: 0

    # - name: "V"
    #   slug: "f-content"
    #   active: 0

    # - name: "W"
    #   slug: "f-content"
    #   active: 0

    # - name: "X"
    #   slug: "f-content"
    #   active: 0

    # - name: "Y"
    #   slug: "f-content"
    #   active: 0

    # - name: "Z"
    #   slug: "f-content"
    #   active: 0
